version: "3.9"
services:
  my_service:
    image: "httpd:alpine3.16"
    ports:
      - "80:80"
    volumes:
      - ${PWD}/e2e/index.html:/usr/local/apache2/htdocs/index.html
  other_service:
    image: "curlimages/curl:7.84.0"
    command: "sh -c 'while true; do date; sleep 2; done'"
    links:
      - my_service
